"""
Django settings for support project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mo@yiy6f_rz-%6dv@5lbr3u82^)r(mp#9^*mt5w$23%nerjdx3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# DEBUG = True
#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    # 'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'mandala.auth',     # 权限认证模块
    # 'center',           # 自己建的模块，做测试用的
    'user_center',      # 用户模块
    'secretary',        # 秘书相关模块
    'recorder',         # 日志信息模块
    'customer',         # 客户信息模块
    'competitor',       # 竞品信息模块
    'sale',             # 商务模块，例如：商务画像
    'notice',           # 钉钉消息通知管理模块，包括消息详情列表、消息通知设置等
    'statistical',      # 数据统计模块，例如熊阳扬每周需要统计的数据
    # 'rest_framework',
    'xman',             # 基于vuejs的管理员模块
    'salerVisit',       # 商务签到拜访模块
    'work_platform',       # 商务工作台
    'financial_statements',    # 财务报表
    'user_log',         # 新后台操作日志
    'product',          # 产品管理模块
    'interface',          # 对外接口
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    'mandala.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 自定义的中间件
    'xman.middleware.SidebarMiddleware',
    #跨域
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = 'support.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',
                'mandala.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'support.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {'ENGINE': 'django.db.backends.mysql',
        'NAME': 'xgyypt',
        'USER': 'root',
        'PASSWORD': '1CzoOCywfJ*h',
        'HOST': '192.168.185.33',
        'PORT':3306,
        'OPTIONS':{'isolation_level':None}
    },
    'yqms2_32': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yqms2',
        'USER': 'fbeta',
        'PASSWORD': '9yacto9659d',
        'HOST': '192.168.30.2',
        'PORT':3306,
        'OPTIONS':{'isolation_level':None}
    },
    'yqht_32': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yqht',
        'USER': 'fbeta',
        'PASSWORD': '9yacto9659d',
        'HOST': '192.168.30.2',
        'PORT':3306,
        'OPTIONS':{'isolation_level':None}
    },

    'contract_33': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'contract',
        'USER': 'root',
        'PASSWORD': '1CzoOCywfJ*h',
        'HOST': '192.168.185.33',
        'PORT':3306,
        'OPTIONS':{'isolation_level':None}
    },

    'crminfo_33': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'crm_info',
        'USER': 'root',
        'PASSWORD': '1CzoOCywfJ*h',
        'HOST': '192.168.185.33',
        'PORT': 3306,
        'OPTIONS': {'isolation_level': None}
    },
    'yqms2_199': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yqms2',
        'USER': 'fuser',
        'PASSWORD': '97yu1r221pxeyt3',
        'HOST': '192.168.16.199',
        'PORT':3306,
        'OPTIONS':{'isolation_level':None}
    },
    'log_120': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'log',
        'USER': 'loguser',
        'PASSWORD': 'f693b823',
        'HOST': 'mysql-yqms-log.istarshine.net.cn',
        # 'HOST': '192.168.19.120',
        'PORT':3306,
        'OPTIONS':{'isolation_level':None}
    },
    'yqht_199': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yqht',
        'USER': 'fuser',
        'PASSWORD': '97yu1r221pxeyt3',
        'HOST': '192.168.16.199',
        'PORT':3306,
        'OPTIONS':{'isolation_level':None}
    },
    'zhwp_new': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'zhwp_new',
        'USER': 'fuser',
        'PASSWORD': '7ga7iv13a5',
        'HOST': '192.168.19.6',
        'PORT': 3306,
        'OPTIONS': {'isolation_level': None}
    },
}

SUB_DIR = os.path.basename(os.path.dirname(__file__))


SUB_DIR = os.path.basename(os.path.dirname(__file__))
DATABASE_ROUTERS = [
    '{}.database_router.DatabaseAppsRouter'.format(SUB_DIR)
]
DATABASE_APPS_MAPPING = {
        # example:
        #'app_label':'database_name',
        # 'admin': 'default',
        # 'auth': 'default',
        # 'contenttypes': 'default',
        # 'sessions': 'default',
        # 'user_center': 'default',
        'competitor': 'contract_33',
        'customer': 'crminfo_33',
        'secretary': 'yqms2_199',
        'recorder': 'log_120',
        'sale': 'contract_33',
        'user_log': 'default',
        'survery': 'yqms2_32',
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'mandala.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'mandala.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'mandala.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'mandala.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = ['mandala.auth.backends.ModelBackend']

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Media files (video, audio ...)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), 
    # os.path.join(BASE_DIR, 'media')
]

# STATIC_ROOT = os.path.join(BASE_DIR, '/static/')
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_ROOT = os.path.join(BASE_DIR, 'static_new')
TMP_DIR = os.path.join(BASE_DIR, 'static/tmp')
# Django的缓存配置

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://192.168.185.117:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "session": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://192.168.185.117:6379/2", # 指明使用redis的1号数据库
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 配置session存储
SESSION_COOKIE_AGE=24 * 60 * 60 #设置session过期时间为30分钟
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# 配置登录url地址
LOGIN_URL='/login'
LOGIN_URL_OLD = "https://support.istarshine.com/Home/Login/login.html"

# 跳到老后台
LOGIN_URL_OLD_BACKEND = "https://support.istarshine.com/Login/fast"

# 新老后台互跳密码 md5 加密盐
LOGIN_SALT = "wcx666"

AUTH_USER_MODEL = 'user_center.UserNew'

# 403页面
URL_403 = '/403.html'
# 403json
JSON_403 = '/json/403'

"""日志"""
from .log import LOGGING

"""以下为各app中相关的配置"""

# 舆情秘书账号的状态
ACCOUNT_STATUS_MAP = {
    "": "",
    None: "",
    "0": "正式",
    "1": "试用",
    "2": "停用",
    "3": "停用",
    "4": "停用",
    "5": "停用",
    "-1": "弃用"
}

# 态势感知账号状态映射
TSGZ_ACCOUNT_STATUS_MAP = {
    "": "",
    None: "",
    "0": "正式",
    "1": "试用",
    "2": "停用",
}

# 智慧网评账号状态映射
ZHWP_ACCOUNT_STATUS_MAP = {
    "": "",
    None: "",
    "0": "试用",
    "1": "正式",
}

# 智慧商情账号状态映射
ZHSQ_ACCOUNT_STATUS_MAP = {
    "": "",
    None: "",
    "0": "试用",
    "1": "正式",
    "2": "停用",
}

# 一级部门
# SALE_DEPARTMENT_LEVEL_1 = {
#         58062185: "政务中心", #政务事业部-销售中心
#         58386915: "企业中心", #企业事业部-销售中心-销售部
# }

# 一级部门
SALE_DEPARTMENT_LEVEL_0 = {
    "政务事业部":58062184, #政务事业部
    "管理层":1136060, #管理层
    "政务销售中心":58062185, #政务销售中心
    "企业事业部":58054275, #企业事业部
}

# 一级部门
SALE_DEPARTMENT_LEVEL_1 = {
        58062185: "政务销售中心", #政务事业部-销售中心
        58034238: "企业销售中心", #企业事业部-销售中心
}

# 账号活跃度统计中操作一列中查看用户
MSUSER_NEXT_URL = "https://support.istarshine.com/Newcustomer/allcustomer?login_name="
# 账号活跃度统计中操作一列中态势感知查看用户
TSGZ_USER_NEXT_URL = "https://support.istarshine.com/Android/index_2019?logname="
# 账号活跃度统计中操作一列中网评查看用户
WP_USER_NEXT_URL = "https://support.istarshine.com/WP/index?orgName="
# 账号活跃度统计中操作一列中客户画像
CRMUSER_NEXT_URL = "https://support.istarshine.com/CustomerPortrait/index?accountId="

# 账号活跃度统计中点击用户名称，跳转到舆情秘书账号首页
YQMS_ACCOUNT_JUMP_URL = "http://yqms.istarshine.com/Login/doLogin?type=logintype&loguser="
# 账号活跃度统计中点击用户名称，跳转到态势感知账号首页
TSGZ_ACCOUNT_JUMP_URL = "http://tsgz.istarshine.com/index.html#/yqmslogin?type=logintype&loguser="
# 账号活跃度统计中点击用户名称，跳转到网评账号首页
WP_ACCOUNT_JUMP_URL = "https://zhwp.istarshine.com/login.do?chkSave=on&loginType=1&loguser="
# 账号活跃度统计中点击客户名称，跳转到销售易账号首页
CRM_CUSTOMER_JUMP_URL = "http://crm.xiaoshouyi.com/final/account.action?id="


# 高德地图插件的key
gd_key = 'e812a2e8a5f61640fc68e09c3572dcf1'

# 对接卢达上传微信群二维码的接口
WECHAT_QR_CODE_UPLOAD_API = "http://push-admin-beta.istarshine.com/api/common/wechat/group"
WECHAT_QR_CODE_UPLOAD_TOKEN = "4a849e31-a3dc-469f-bc6a-9ebd8a3de8c0"

# 接收卢达绑定微信群二维码的结果的通知时，卢达需要携带的token
WECHAT_QR_CODE_UPLOAD_RESULT_TOKEN = "4a849e31-a3dc-469f-bc6a-9ebd8a3de8c1"

# 上传微信群二维码时，将结果保存到redis
WECHAT_QR_CODE_BINDING_RESULT_REDIS_URL = "redis://192.168.185.117:6379/1"
WECHAT_QR_CODE_BINDING_RESULT_HASH = "wechat_qr_code_binding_result_hash_beta"
WECHAT_QR_CODE_TASK_CUSTOMER_HASH = "wechat_qr_code_task_customer_hash_beta"

# 当微信群绑定成功之后，24小时审核期之后，需要钉钉通知销售
# 需要将审核任务存放到redis中，定时脚本去定时检测
WECHAT_QR_CODE_VERIFING_TASK_LIST = "wechat_qr_code_verifing_task_list"

#微信群消息推送
WECHAT_GROUP_MESSAGE_PUSH_REDIS_URL = "redis://192.168.187.201/0"
WECHAT_GROUP_MESSAGE_PUSH_LIST = "yqms_warning_push_test"

#钉钉H5应用参数：
APP_KEY = ""
APP_SECRET = ""