# Generated by Django 2.2.4 on 2020-01-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DingGroupMemberMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.TextField(verbose_name='钉钉部门ID')),
                ('group_name', models.TextField(verbose_name='钉钉部门名称')),
                ('sub_group_ids', models.TextField(verbose_name='下级部门ID')),
                ('sub_group_names', models.TextField(verbose_name='下级部门名称')),
                ('sub_group_ids_all', models.TextField(verbose_name='所有下级部门ID')),
                ('sub_group_names_all', models.TextField(verbose_name='所有下级部门名称')),
                ('member_ids', models.TextField(verbose_name='部门成员ID')),
                ('member_names', models.TextField(verbose_name='部门成员名字')),
                ('member_ids_all', models.TextField(verbose_name='所有成员ID')),
                ('member_names_all', models.TextField(verbose_name='所有成员名字')),
            ],
            options={
                'db_table': 'ding_group_member_map',
                'managed': False,
            },
        ),
    ]
