# Generated by Django 2.2.4 on 2020-02-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200211_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '客户管理模块特殊权限',
                'verbose_name_plural': '客户管理模块特殊权限',
                'db_table': 'customer_app_access',
            },
        ),
    ]
