# Generated by Django 2.2.4 on 2020-01-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0002_auto_20200103_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$3XM4yFa5lupA$DWjzQQRRCfHBP1IA7g16BLaGEIPy3LEXGO87YRJg5XI=', max_length=128, verbose_name='密码'),
        ),
    ]
