# Generated by Django 2.2.4 on 2020-01-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0004_auto_20200106_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernew',
            name='gid',
        ),
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$xKuNGBwJXDMG$enALCOk8Y8uT3o/uf95UJHFxUbLpIPi107qQLg6IiqU=', max_length=128, verbose_name='密码'),
        ),
    ]
