# Generated by Django 2.2.4 on 2020-01-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0008_auto_20200108_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationinfo',
            options={},
        ),
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$gYFTBhAVqzA8$B+dJXYCVMWQXfRlEVpKkB8w/cexvpAjNbVIOZucd9XU=', max_length=128, verbose_name='密码'),
        ),
    ]
