# Generated by Django 2.2.4 on 2020-01-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0014_auto_20200109_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$fuVOh9HgD4HW$PaQTguQD2Kz8GcZPFNdP6DPFcYf9t43mIHGg6fSTKpY=', max_length=128, verbose_name='密码'),
        ),
    ]
