# Generated by Django 2.2.4 on 2020-01-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0015_auto_20200109_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$GUTMBVJcZFkx$lmE8bICliGwmZ7EnP23QjOhnUYs+vkI4VZQhrTQFvEQ=', max_length=128, verbose_name='密码'),
        ),
    ]
