# Generated by Django 2.2.4 on 2020-02-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('user_center', '0017_auto_20200211_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$tXNXQrFBaTw8$f3mcce/LUPrMHDDAUeWnGC+NWdGZZ6NYx4qLYUYee/8=', max_length=128, verbose_name='新后台密码'),
        ),
        migrations.AlterField(
            model_name='usernew',
            name='status',
            field=models.IntegerField(blank=True, null=True, verbose_name='用户状态'),
        ),
        migrations.CreateModel(
            name='SiderBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('icon', models.CharField(blank=True, max_length=20, null=True, verbose_name='图标')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_center.SiderBar', verbose_name='父标签')),
                ('perm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '侧边栏',
                'verbose_name_plural': '侧边栏',
                'db_table': 'sider_bar',
            },
        ),
    ]
