# Generated by Django 2.2.4 on 2020-02-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0018_auto_20200211_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siderbar',
            name='icon',
            field=models.CharField(blank=True, default='fa-circle-o', max_length=20, null=True, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$6yGATcTMFXOW$nrrZVxrtV0L6e9BuZpQjCccJAHdHGO3MF4U5dM9c6Kw=', max_length=128, verbose_name='新后台密码'),
        ),
    ]
