# Generated by Django 2.2.4 on 2020-02-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0020_auto_20200213_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model')),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True, verbose_name='动作')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='详情')),
                ('user_id', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='用户ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户操作记录',
                'verbose_name_plural': '用户操作记录',
                'db_table': 'user_log',
            },
        ),
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$Iu7NDMVSSnWs$dH5z4VUWQ6M6S+F6J8bBxCtFlP6fyVpuSfHhGtEZUmE=', max_length=128, verbose_name='新后台密码'),
        ),
    ]
