# Generated by Django 2.2.4 on 2020-02-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0022_auto_20200218_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='message',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$fTmCUxf2TQOt$NVvgBiWWP/xffXOrOs8NodyeY/JP5+Ajcfxz8zgRSIc=', max_length=128, verbose_name='新后台密码'),
        ),
    ]
