# Generated by Django 2.2.4 on 2020-01-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0010_auto_20200108_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$vgbzsRcKiBvF$rPO6ICEv3gMACJuxdXYgXhydiUuLsxcex2EnBomap/E=', max_length=128, verbose_name='密码'),
        ),
    ]
