# Generated by Django 2.2.4 on 2020-01-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0013_auto_20200108_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$G8Wk8cL3XCmF$p6dU6vuSCZG6U8ULTjFDhmtI54Ooyq18cFBDzHv+sfY=', max_length=128, verbose_name='密码'),
        ),
    ]
