# Generated by Django 2.2.4 on 2020-02-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0016_auto_20200109_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationinfo',
            options={'verbose_name': '地域信息', 'verbose_name_plural': '地域信息'},
        ),
        migrations.AlterModelOptions(
            name='usernew',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$ojgPgGm6GyT3$4zpGaNSdPENJU7Qs734sttJBQmN0nhdoitGX8ymhN2E=', max_length=128, verbose_name='密码'),
        ),
    ]
