# Generated by Django 2.2.4 on 2020-02-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0021_auto_20200218_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$dnxO3cnafwHk$/rQvjsM+OSnLaQ7m1ngxSZVlKjhXaaCAKS+uxWLmzPs=', max_length=128, verbose_name='新后台密码'),
        ),
    ]
