# Generated by Django 2.2.4 on 2020-07-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0024_auto_20200708_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernew',
            name='istarshine_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='unique_id'),
        ),
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$5stRAqeWxOE3$QpA/WNofaOh+U4TTpRg9GDXtn7gS2N29nDOiEgdRqUY=', max_length=128, verbose_name='新后台密码'),
        ),
    ]
