# Generated by Django 2.2.4 on 2020-07-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0025_auto_20200708_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernew',
            name='ehr_department_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ehr_department_code'),
        ),
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$wy64ysed1WvZ$39Sc1Tr5/Lg7zxzLJ/fBhDnpsqYcxcATvHx+KNbRASk=', max_length=128, verbose_name='新后台密码'),
        ),
    ]
