# Generated by Django 2.2.4 on 2020-03-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeAppAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '通知管理模块特殊权限',
                'verbose_name_plural': '通知管理模块特殊权限',
                'db_table': 'notice_app_access',
            },
        ),
        migrations.CreateModel(
            name='NoticeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ding_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='钉钉用户ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='消息内容')),
                ('notice_type', models.IntegerField(default=0, verbose_name='消息类型')),
                ('object_type', models.IntegerField(default=0, verbose_name='关联对像的类型')),
                ('object_id', models.IntegerField(default=0, verbose_name='关联对像的ID')),
                ('status', models.IntegerField(default=0, verbose_name='钉钉通知是否发送成功，0、不发送（对应用户已经设置了禁止钉钉发送通知的情况），1、发送成功，2、发送失败')),
            ],
            options={
                'db_table': 'notice_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NoticeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ding_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='钉钉用户ID')),
                ('notice_type', models.IntegerField(default=0, verbose_name='消息类型')),
                ('status', models.IntegerField(default=1, verbose_name='开关是否接收消息 0、关闭，1、开启')),
            ],
            options={
                'db_table': 'notice_setting',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NoticeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='钉钉通知的类型名称')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='关于此消息类型的具体描述')),
            ],
            options={
                'db_table': 'notice_type',
                'managed': True,
            },
        ),
    ]
