# Generated by Django 2.2.4 on 2020-03-18 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticelist',
            name='ding_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='dtalkid', verbose_name='钉钉用户ID'),
        ),
        migrations.AlterField(
            model_name='noticesetting',
            name='ding_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='dtalkid', verbose_name='钉钉用户ID'),
        ),
        migrations.AlterField(
            model_name='noticetype',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='钉钉通知的类型名称'),
        ),
    ]
