# Generated by Django 2.2.4 on 2020-03-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20200318_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticelist',
            old_name='ding_id',
            new_name='ding_user',
        ),
        migrations.RenameField(
            model_name='noticesetting',
            old_name='ding_id',
            new_name='ding_user',
        ),
    ]
