# Generated by Django 2.2.4 on 2020-03-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20200318_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticelist',
            options={'managed': True, 'verbose_name': '钉钉通知列表', 'verbose_name_plural': '钉钉通知列表'},
        ),
        migrations.AlterModelOptions(
            name='noticesetting',
            options={'managed': True, 'verbose_name': '钉钉通知设置', 'verbose_name_plural': '钉钉通知设置'},
        ),
        migrations.AlterModelOptions(
            name='noticetype',
            options={'managed': True, 'verbose_name': '钉钉通知类型', 'verbose_name_plural': '钉钉通知类型'},
        ),
        migrations.AlterField(
            model_name='noticelist',
            name='notice_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='noticelist',
            name='object_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='关联对像的ID'),
        ),
        migrations.AlterField(
            model_name='noticelist',
            name='object_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='关联对像的类型'),
        ),
        migrations.AlterField(
            model_name='noticelist',
            name='status',
            field=models.IntegerField(blank=True, null=True, verbose_name='钉钉通知是否发送成功，0、不发送（对应用户已经设置了禁止钉钉发送通知的情况），1、发送成功，2、发送失败'),
        ),
        migrations.AlterField(
            model_name='noticesetting',
            name='notice_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='noticesetting',
            name='status',
            field=models.IntegerField(blank=True, null=True, verbose_name='开关是否接收消息 0、关闭，1、开启'),
        ),
    ]
