# Generated by Django 2.2.4 on 2020-03-19 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20200318_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticelist',
            name='ding_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='dtalkid', verbose_name='钉钉用户'),
        ),
        migrations.AlterField(
            model_name='noticelist',
            name='notice_type',
            field=models.ForeignKey(blank=True, db_column='notice_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notice.NoticeType', verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='noticelist',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '不发送'), (1, '发送成功'), (2, '发送失败')], null=True, verbose_name='发送状态'),
        ),
        migrations.AlterField(
            model_name='noticesetting',
            name='ding_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='dtalkid', verbose_name='钉钉用户'),
        ),
        migrations.AlterField(
            model_name='noticesetting',
            name='notice_type',
            field=models.ForeignKey(blank=True, db_column='notice_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notice.NoticeType', verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='noticesetting',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '关闭'), (1, '开启')], null=True, verbose_name='是否接收消息'),
        ),
    ]
