# Generated by Django 2.2.4 on 2020-03-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_noticelist_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticelist',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发送时间'),
        ),
    ]
