# Generated by Django 2.1 on 2020-02-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitorname', models.CharField(blank=True, db_column='competitorName', max_length=100, null=True, verbose_name='竞品名称')),
                ('competitorproduct', models.CharField(blank=True, db_column='competitorProduct', max_length=255, null=True, verbose_name='竞品产品')),
            ],
            options={
                'db_table': 'competitor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CrmCompetitorMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.CharField(blank=True, db_column='accountId', max_length=100, null=True, verbose_name='客户id')),
                ('competitorid', models.CharField(blank=True, db_column='competitorId', max_length=100, null=True, verbose_name='竞品id')),
                ('competitorname', models.CharField(blank=True, db_column='competitorName', max_length=100, null=True, verbose_name='竞品名')),
                ('competitorproductid', models.CharField(blank=True, db_column='competitorProductId', max_length=100, null=True, verbose_name='竞品签单产品id')),
                ('competitorproduct', models.CharField(blank=True, db_column='competitorProduct', max_length=100, null=True, verbose_name='竞品签单产品')),
                ('competitormoney', models.CharField(blank=True, db_column='competitorMoney', max_length=100, null=True, verbose_name='竞品签单金额')),
                ('competitordate', models.CharField(blank=True, db_column='competitorDate', max_length=100, null=True, verbose_name='竞品签单日期')),
            ],
            options={
                'db_table': 'crm_competitor_map',
                'managed': True,
            },
        ),
    ]
