# Generated by Django 2.2.4 on 2020-07-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitAppAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '签到地图模块特殊权限',
                'verbose_name_plural': '签到地图模块特殊权限',
                'db_table': 'visit_app_access',
            },
        ),
    ]
